
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwfoivwamwlslbemutmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3Zm9pdndhbXdsc2xiZW11dG1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDA0MDcsImV4cCI6MjA2Mzg3NjQwN30.r0e9W6f81vdXM9NnIYtMNkETE_CnHlJmXJO68pm_fKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
