// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlzskkppbxvxytgcdsvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsenNra3BwYnh2eHl0Z2Nkc3ZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2ODM4NzgsImV4cCI6MjA2MzI1OTg3OH0.-Tsrha_avi4MfJazQ4U0ITSlEtmfXn9HJyJblqE56U8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);